# site settings
title: Sochan Mao
subtitle: 11+ years’ IT professional experiences
email: sochan.mao@gmail.com
description: Master of IT (Professional), Deakin University (Melbourne, Australia), Web and Windows application, Mobile Application, JavaScript, C#, NodeJS, ReactJS, .NET CORE, Python, JAVA, C++, C, IBM Cloud, Google Cloud, AZURE, MVC, MVVM, HTML5, jQuery, Bootstrap, CSS, OOP, Lua.
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author:
street_address: Noble Park, Victoria
city: Melbourne
state: VIC
zip_code: 3174
country: Australia
phone: (61) 411 469 999

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://github.com/sochan
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/sochanmao/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/sochanGuru

# build settings
markdown: kramdown

sass:
  style: compressed
